### ISSUE TITLE
How to get section metadata such as spacing?

### ISSUE THREAD

**Issue by MattTheCuber** [Auxilia-tech/pyDICOS#35]
### Search before asking

- [X] I have searched the [issues](https://github.com/Auxilia-tech/pyDICOS/issues) and [discussions](https://github.com/Auxilia-tech/pyDICOS/discussions) and found no similar questions.

### Question

How do I retrieve the following metadata for a section in a CT scan?

- KVP
- Position
- Slice Thickness
- Slicing Direction
- Spacing

```py
from pydicos import dcsread

ct = dcsread(path)
section = ct.GetSectionByIndex(0)
section.GetSpacingInMM()  # Not defined, SetSpacingInMM is defined though.
```

**Comment by lcombaldieu** [comment]
Hi @MattTheCuber,
We did not translate the SectionCommon class with pybind. 
We will open a request for this task, this should not take long.
Thank you for your interest

**Comment by lcombaldieu** [comment]
@MattTheCuber The missing functions were added in [PR#38](https://github.com/Auxilia-tech/pyDICOS/pull/38). 
Don't hesitate to contribute to the project and give feedback.
I'm closing the issue.

**Comment by MattTheCuber** [comment]
Does a TDR scan have spacing or that a CT property only?

**Comment by lcombaldieu** [comment]
@MattTheCuber to my knowledge, no. You have to query the linked CT to retrieve the spacing. I figure this design reduces redundancy.
